from colors import *

print(BLACK)
print("black")
print(RED)
print("red")
print(GREEN)
print("green")
print(BROWN)
print("brown")
print(BLUE)
print("blue")
print(PURPLE)
print("purple")
print(CYAN)
print("cyan")
print(LIGHT_GRAY)
print("light gray")
print(LIGHT_RED)
print("light red")
print(LIGHT_GREEN)
print("light green")
print(YELLOW)
print("yellow")
print(LIGHT_BLUE)
print("light blue")
print(LIGHT_PURPLE)
print("light purple")
print(LIGHT_CYAN)
print("light cyan")
print(LIGHT_WHITE)
print("light white")
print(DEFAULT)
print("default")
